version: '3.3'
services:
    openai:
        build: ./services/openai/
        volumes:
            - ./services/openai/:/usr/src/app/
        ports:
            - "5700:5700"
        environment:
            PORT: 5700
            FLASK_DEBUG: 1
        env_file:
            - .env
    todoist:
        depends_on:
        - "openai"
        build: ./services/todoist/
        volumes:
            - ./services/todoist/:/usr/src/app/
        ports:
            - "5702:5702"
        environment:
            PORT: 5702
            FLASK_DEBUG: 1
        env_file:
            - .env
    apis:
        depends_on:
        - "openai"
        - "todoist"
        build: ./services/apis/
        volumes:
            - ./services/apis/:/usr/src/app/
        ports:
            - "5701:5701"
        environment:
            PORT: 5701
            FLASK_DEBUG: 1
        env_file:
            - .env